[tox]
envlist = py312

[testenv]
usedevelop=True

[testenv:py{311,312,313}]
runner = uv-venv-lock-runner
extras = d3, mace, plumed, chgnet, grace, orb
with_dev = True
description = Run the test suite against Python versions
commands = pytest {posargs} --cov janus_core --import-mode importlib

[testenv:e3nn]
runner = uv-venv-lock-runner
extras = mattersim
with_dev = True
description = Run the test suite against MLIPs with updated e3nn (incompatible with MACE)
commands = pytest tests/test_mlip_calculators.py tests/test_single_point.py {posargs} --cov janus_core --import-mode importlib

[testenv:upet]
runner = uv-venv-lock-runner
extras = d3, upet
with_dev = True
description = Run the test suite against UPET (incompatible with Orb)
commands = pytest tests/test_mlip_calculators.py tests/test_single_point.py {posargs} --cov janus_core --import-mode importlib

[testenv:deepmd]
runner = uv-venv-lock-runner
extras = deepmd
with_dev = True
description = Run the test suite against DeePMD-kit (incompatible with MACE and fairchem)
commands = pytest tests/test_mlip_calculators.py tests/test_single_point.py {posargs} --cov janus_core --import-mode importlib

[testenv:pre-commit]
runner = uv-venv-lock-runner
extras = d3, mace, plumed, chgnet, grace, orb
with_dev = True
description = Run the pre-commit checks
commands = pre-commit run {posargs} --all-files

[testenv:docs]
runner = uv-venv-lock-runner
extras = d3, mace, plumed, chgnet, grace, orb
with_dev = True
description = Build the documentation
commands = sphinx-build -nW --keep-going -b html {posargs} docs/source docs/build/html
