FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

LABEL maintainer="Alin Elena <alin@elena.re>"
ARG UID="1001"
ARG GID="100"

ENV user=drFaustroll
ENV group=drFaustroll
RUN useradd -m ${user}
WORKDIR /app

USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update --yes && \
    apt upgrade --yes && \
    apt install --yes --no-install-recommends \
    ca-certificates \
    locales \
    sudo \
    tini \
    wget bzip2 curl git gcc g++ make cmake   && \
    apt clean && rm -rf /var/lib/apt/lists/* && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen


ARG marimo_version=0.16.4
ENV MARIMO_SKIP_UPDATE_CHECK=1
ENV UV_SYSTEM_PYTHON=1
RUN uv pip install --no-cache-dir marimo==${marimo_version} && \
  mkdir -p /app/data && \
  chown -R ${user}:${group} /app

COPY --chown=${user}:${group} assets/tutorials tutorials

ENV PORT=8842
EXPOSE $PORT

ENV HOST=0.0.0.0

RUN uv pip install --no-cache-dir marimo[recommended,lsp,sql] altair pandas python-lsp-server websockets \
  duckdb \
  sqlglot \
  vegafusion vl-convert-python \
  ruff \
  openai \
  nbformat \
  pytest
RUN uv pip install --no-cache-dir 'janus-core[chgnet,dpa3,d3,grace,mace,orb,pet-mad,plumed]@git+https://github.com/stfc/janus-core.git@main'
RUN uv pip install  --no-cache-dir cuequivariance==0.5.1 \
  cuequivariance-torch==0.6.1 \
  cuequivariance-ops-torch-cu12==0.6.1 \
  torchvision \
  pack-mm \
  seaborn \
  data-tutorials \
  pymatviz \
  opentsne \
  pymatgen \
  pymatviz \
  git+https://github.com/imagdau/aseMolec@main

CMD ["/bin/sh", "-c", "exec marimo edit --no-token -p $PORT --host $HOST"]
