name: ghcr-jupyter
on:
  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'clone the repo'
        uses: actions/checkout@v4
      - name: 'login to ghcr'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./containers
          file: ./containers/Dockerfile.jupyter
          push: true
          tags: |
            ghcr.io/stfc/janus-core/jupyter:${{ github.sha }}
            ghcr.io/stfc/janus-core/jupyter:latest
