name: self-ci

on: [push, pull_request]

jobs:

  tests:
    runs-on: self-hosted
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.9','3.10','3.11','3.12']
    container: python:${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4

    - name: set path
      run: |
          echo "/github/home/.local/bin" >> $GITHUB_PATH

    - name: Install python dependencies
      run: |
        echo "/github/home/.local/bin" >> $GITHUB_PATH
        python3 -m pip install pipx
        pipx install poetry
        poetry env use ${{ matrix.python-version }}
        poetry install --with dev

    - name: Run test suite
      env:
        # show timings of tests
        PYTEST_ADDOPTS: "--durations=0"
      run: |
        poetry run pytest --cov janus_core --cov-append .

    - name: Report coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        parallel: true
        flag-name: run-${{ matrix.python-version }}
        file: coverage.xml
        base-path: janus_core

  coverage:
    needs: tests
    runs-on: self-hosted
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
